### PR TITLE
feat: Upgrade from Jekyll 3.x to 4.x

### PR DESCRIPTION
**Pull request by smockle**
### Rationale

Jekyll 4.x allows Catalyst to [use Kramdown 2.3.0](https://jekyllrb.com/docs/upgrading/3-to-4/#kramdown-v2), as suggested by [CVE 2020-14001](https://github.com/advisories/GHSA-mqm2-cgpr-p4m6).

### Jekyll 3.x to 4.x Upgrade Guide

The [upgrade guide](https://jekyllrb.com/docs/upgrading/3-to-4) notes several changes:

- **[Ruby ≥2.5.0 required](https://jekyllrb.com/docs/upgrading/3-to-4)** — Catalyst could add a [`.ruby-version` file](https://github.com/rbenv/rbenv#choosing-the-ruby-version) to make this requirement explicit, though since Ruby 2.5.0 was [released](https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/) in 2017, I imagine many folks already have a newer version installed—anecdotally, I did.

- **[`post_url` now prepends `site.baseurl`](https://jekyllrb.com/docs/upgrading/3-to-4)** — `git grep post_url` did not show any matches, so this change does not (directly) affect Catalyst.

- **[Templates are now parsed once, then cached and rendered multiple times](https://jekyllrb.com/docs/upgrading/3-to-4/#template-rendering)** — I don’t know how to asses the impact of this. The description for this change mentions some plugins may behavior differently as a result. [`docs/_config.yml`](https://github.com/github/catalyst/blob/88233801ddc8408ebbbcccd9a4a39de0fd4d7fea/docs/_config.yml#L25-L26) lists one plugin, [`jekyll-github-metadata`](https://github.com/jekyll/github-metadata).

- **[Collections (other than `posts`) not configured with `output: true` aren’t outputted](https://jekyllrb.com/docs/upgrading/3-to-4/#static-files-in-unrendered-collections)** — Catalyst’s [`guide` collection](https://github.com/github/catalyst/blob/88233801ddc8408ebbbcccd9a4a39de0fd4d7fea/docs/_config.yml#L15-L17) is configured with `output: true`, so this change does not affect Catalyst.

- **[`site.liquid_renderer.file(path).parse(content)` is now idempotent (for `path`)](https://jekyllrb.com/docs/upgrading/3-to-4/#for-plugin-authors)** — `git grep liquid_renderer` did not show any matches, so this change does not (directly) affect Catalyst. Additionally, the description for this change mentions it is relevant to plugin authors, but this is a Jekyll site, not a plugin.

- **[`exclude` in `_config.yml` is now additive, and the default exclude list has expanded](https://jekyllrb.com/docs/upgrading/3-to-4/#exclusion-changes)** — [`docs/_config.yml`](https://github.com/github/catalyst/blob/88233801ddc8408ebbbcccd9a4a39de0fd4d7fea/docs/_config.yml#L10-L13)’s `exclude` configuration is now redundant and can be removed, though I haven’t to keep this changeset small and testable/reviewable.

- **[Jekyll dropped support for Kramdown 1.x](https://jekyllrb.com/docs/upgrading/3-to-4/#kramdown-v2)** — This was the precipitating reason for this PR, as described above. It’s worth noting that Kramdown 2.0.0 introduced its own set of [breaking changes](https://kramdown.gettalong.org/news.html#kramdown-200-released).

- **[Deprecated configuration options have been removed](https://jekyllrb.com/docs/upgrading/3-to-4/#deprecated-configuration-options)** — [`docs/_config.yml`](https://github.com/github/catalyst/blob/main/docs/_config.yml) does not include any deprecated configuration options, so this change does not affect Catalyst.

### 🚨 Before Merging 🚨

While testing this branch locally, I’ve noticed the following unexpected behavior, which we should investigate further before merging:

1. ~The warning `GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.` is logged when running `bundle exec jekyll build` or `bundle exec jekyll serve` in the `docs` directory.~ (Update: Ignoring, as [advised](https://github.com/github/catalyst/pull/90#pullrequestreview-547288813))

2. ~Instead of navigating, clicking the “Reference” button on http://127.0.0.1:4000 duplicates the heading (GIF below). No errors appear in Terminal or the Safari Developer Tools Console.~ (Update: Fixed in https://github.com/github/catalyst/pull/90/commits/b7fc3d4667fced16fe1eb04d07474bb8d5d992e0)

catalyst-heading-duplicated

### CODE REVIEW

**Review by koddsson — APPROVED** [review]
This seems good to me 👍🏻 

> 1. The warning `GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.` is logged when running `bundle exec jekyll build` or `bundle exec jekyll serve` in the `docs` directory.

I think this is fine if the page is otherwise working.

> 2\. Instead of navigating, clicking the “Reference” button on http://127.0.0.1:4000 duplicates the heading (GIF below). No errors appear in Terminal or the Safari Developer Tools Console.

I can't reproduce locally 🤷🏻

**Review by keithamus — APPROVED** [review]
:+1:

**Comment by smockle** [comment]
> > 2. Instead of navigating, clicking the “Reference” button on http://127.0.0.1:4000 duplicates the heading (GIF below). No errors appear in Terminal or the Safari Developer Tools Console.
> 
> I can't reproduce locally 🤷🏻

I can consistently repro it in Safari. It seems to be caused by the `<br class="hide-sm">` [in `index.html`](https://github.com/github/catalyst/blob/79f919ccb08274d05108490a5946fd096fd43789/docs/index.html#L6)—when I remove that break, things work as expected. Still debugging to figure out what’s going on, but I don’t think it’s related/caused by this PR’s update to Jekyll 4.x.

**Comment by smockle** [comment]
> > > 1. Instead of navigating, clicking the “Reference” button on http://127.0.0.1:4000 duplicates the heading (GIF below). No errors appear in Terminal or the Safari Developer Tools Console.
> > 
> > 
> > I can't reproduce locally 🤷🏻
> 
> I can consistently repro it in Safari when the viewport is wider than `1280px`. It seems to be related to the `<br class="hide-sm">` [in `index.html`](https://github.com/github/catalyst/blob/79f919ccb08274d05108490a5946fd096fd43789/docs/index.html#L6)—when I remove that break, things work as expected. Still debugging to figure out what’s going on, but I don’t think it’s related/caused by this PR’s update to Jekyll 4.x.
> 
> I suspect it’s something like [Flexbug #11](https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items):
> 
> > Safari uses min/max width/height declarations for actually rendering the size of flex items, but it ignores those values when calculating how many items should be on a single line of a multi-line flex container. Instead, it simply uses the item's `flex-basis` value, or its `width` if the flex basis is set to auto.

Update: Fixed in https://github.com/github/catalyst/pull/90/commits/b7fc3d4667fced16fe1eb04d07474bb8d5d992e0

**Pull request merged**
