### PR TITLE
Return object on decorators

### PR DESCRIPTION
**Pull request by vmsp**
This makes the decorators compatible with Babel's Typescript converter.

### CODE REVIEW

**Comment by koddsson** [comment]
This looks like a fair enough change in order for us to support the babel toolchain but I'd like to read more about this issue if possible. Is this difference from TypeScript decorators documented somewhere?

**Comment by ryanluker** [comment]
@koddsson This is also an issue for us as well where we use babel and webpack to transpile our coce.
If I make the change, from the PR, the target decorator starts to work again and we dont need to setup our own manual getters.

**Comment by keithamus** [comment]
Confirmed this behaviour in the [Babel repl](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAdxlAFnEUD6AnAUyhDzAAoAHPOKOAGkQGsCBPASkQG8AoRRAeQBGAKwLQAdABMCwGGAIAFahQJ4oLStVoNmLBp0QBzImQ4HCxUogCMiAL7223O926hIsBCjTp8REuRUNPRMrGa8iBYBAiJiUFIycorKquqawTqs-kYmZpH-VrYOdk4uEAA2AIYAztWIAGJwcFwRAAKoGFi4UVbATW0dvj1IgpV4iM6uEAjVcOUE4uVwhmTyyA1NpuJ9IWsbcFujeGxAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.14&externalPlugins=)

```js
function without_return(proto, key) {
  Object.defineProperty(proto, key, { get() { return 1 } })
}

function with_return(proto, key) {
  return Object.defineProperty(proto, key, { get() { return 1 } })
}
class Foo {
  @without_return foo
  @with_return bar 
}

console.log(new Foo().foo, new Foo().bar)
// Logs `undefined, 1`.
```

The same code in the [TypeScript playground](https://www.typescriptlang.org/play?strictPropertyInitialization=false#code/GYVwdgxgLglg9mABAdxlAFnEUD6AnAUyhDzAAoAHPOKOALkTgCMArA6AGkQGsCBPBgGcoeGGADmASgYA3ODAAmiAN4AoRIgDyrdlAB0CgsDEEACtQoE8UPpWq0uvPl2WJxRMpJWJCxUogBGRABfEMlVYNVVUEhYBBQ0dHwiEnIqGnpGHU4efiERMSlZeSU1DV9UrWz9Q2MwMwsrGzsMx34XNw8vVwr-INDg8MiIABsAQ0FBRAAxODgVdUQAAVQMLFxepGA5hjGwPkWVxOS-JCYxvF39iKiIBEE4EYI9EbhxMnrkGbnPPW24Lifb5wX7nPDhAD0EMQABk3lMAAbgWomBRcAIIvRAA) logs `1, 1`.

**Review by keithamus — APPROVED** [review]

**Comment by ryanluker** [comment]
@keithamus Thanks a bunch for getting this one in!
One thought I had was around if we needed to update the return type on these functions now :thinking: .
https://github.com/github/catalyst/blob/main/src/target.ts#L10
`defineProperty(o: any, p: PropertyKey, attributes: PropertyDescriptor & ThisType<any>): any;`
Given we are returning the result from the `defineProperty` call now but I am not 100% sure of this :grin: .

**Comment by keithamus** [comment]
Changing the signature effects TypeScript as it expects property decorators to return `void`.

**Pull request merged**
