### PR TITLE
Add note on using build manglers

### PR DESCRIPTION
**Pull request by richardhj**
Changed the docs to inform about #98.

Things to consider:
- Introduce a warning.md instead of callout.md
- Move the added section to the "Patterns" page (aka Best-Practices)

### CODE REVIEW

**Comment by keithamus** [comment]
This is a great addition to the docs!

I wonder if we can place this somewhere different, so there aren’t two call outs right next to each other?

**Comment by koddsson** [comment]
> I wonder if we can place this somewhere different, so there aren’t two call outs right next to each other?

@richardhj; what do you think about moving this callout to https://github.github.io/catalyst/guide/you-will-need/. It could even be a section on that page. Maybe a section called something like: "Build considerations."

**Comment by richardhj** [comment]
Will update this PR :)

**Comment by richardhj** [comment]
Updated! 😊

**Comment by jdanyow** [comment]
@keithamus would you be open to exporting more of `controller`'s dependencies so folks could build their own version of the decorator more easily?

Scope hoisting used by bundlers like parcel often transform the class names prior to using terser to compress/mangle. The keep_classnames option is too late in these cases. 

Below are a couple of examples produced by parcel production and dev builds which are incompatible with the controller decorator.
``` js
class $987077569154e2a48a9daba6424caacd$export$786b1b244820acf3 extends HTMLElement {
...
let SideBarElement = class SideBarElement1 extends HTMLElement {
```

**Comment by keithamus** [comment]
> @keithamus would you be open to exporting more of `controller`'s dependencies so folks could build their own version of the decorator more easily?
>

I think that's a great idea. We're always open to new PRs 👍

**Comment by keithamus** [comment]
Looks like this fell off the radar of being merged. Thanks again @richardhj for the contribution!

**Pull request merged**
