### PR TITLE
tweak css sidebar to be responsive

### PR DESCRIPTION
**Pull request by keithamus**
This tweaks the sidebar to handle different screen sizes a little better, and avoid underscrolling during page scroll.

### CODE REVIEW

**Comment by primer-css** [comment]
:wave: Hello and thanks for pinging us! This issue or PR has been added to our inbox and a Design Infrastructure first responder will review it soon.
- :art: **If this is a PR that includes a visual change**, please make sure to add screenshots in the description or deploy this code to a lab machine with instructions for how to test.
- :fast_forward: **If this is a PR that includes changes to an interaction**, please include a [video recording](https://support.apple.com/en-us/HT208721) in the description.
- :warning: **If this is urgent**, please visit us in [#primer](https://github.slack.com/archives/CSGAVNZ19) on Slack and tag the first responders listed in the channel topic.

**Comment by lukasoppermann** [comment]
Seems legit to me, but this is not primer related as far as I can tell. Better if somebody who knows takes a look. Like @koddsson

**Comment by keithamus** [comment]
Catalyst is now within Primer's AOR :smile_cat:

**Comment by lukasoppermann** [comment]
> Catalyst is now within Primer's AOR 😸 

Ups. 🤷

**Review by lukasoppermann — APPROVED** [review]

**Pull request merged**
