### PR TITLE
Observe properties

### PR DESCRIPTION
**Pull request by keithamus**
### What?

This adds the `@observeProperties` decorator - which is automatically called by `@controller`. This decorator takes any property named in the `observedProperties` static array of the class, and observes changes to them, calling `propertyChangedCallback`.

This also adds the `@prop` decorator, which when added to a class field or getter/setter will add that property name to the `observedProperties` array, thereby making it observable.

### Why?

This adds data binding to Catalyst, which will be a pivotal feature for template creation!

### CODE REVIEW

**Comment by rektide** [comment]
i feel like stencil-todo-mvc may be some evidence to help justify the need/use of something like this.

it's a simple todo app. at the heart of it is [TodoModelImpl](https://github.com/yoavaa/stencil-todo-mvc/blob/master/src/index.ts). the controller logic to add & remove todo items is easy enough to understand. but there's a additional layer of concern mixed in to the code, which is their onChanges system. it touches a large amount of the code, making the model significantly harder to understand. it'd be nice to have some kind of observability tools we can readily reach for; it feels like TodoModelImpl had to go off & build some thing to notify others about changes when they got there.

> Some of this code will live on, but not in this manner.

please let us know, as they develop, what follow up pieces of code you find that relates to this `@prop` decorator & it's propertyChangedCallback. one thought i have already is that i might be interested in a way to notify about changes via a Custom Events? the propertyChangedCallback seems like multiple folks who interface with a component might fight over monkeypatching that callback, where-as Custom Events are naturally multi-dispatch.

**Comment by keithamus** [comment]
> please let us know, as they develop

Right now we're exploring property decorators which map to attribute getter/setters. We are finding it more and more important to keep the DOM as the single source of truth and maintaining state internal to a class can cause synchronisation issues. The other benefit of attributes is they already include much of this code (via `attributeChangedCallback` etc.)

**Comment by rektide** [comment]
> We are finding it more and more important to keep the DOM as the single source of truth

Sounds like music to my ears!

I'm also hoping, with this path, that perhaps the standard [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) will be able to fill in for this need to sync systems, stream changes, create responsiveness/reactiveness.

**Comment by keithamus** [comment]
The successor to this PR is here: https://github.com/github/catalyst/pull/103. It does not leverage `MutationObserver` as it doesn't need to (we do leverage `MutationObserver` elsewhere in the codebase to keep `data-actions` synced, though).

**Pull request closed without merging**
