### PR TITLE
feat: Support light and dark color schemes

### PR DESCRIPTION
**Pull request by smockle**
### Description

🎨 General UI colors (and the corresponding variable names) are inspired by [GitHub’s recently-announced dark mode](https://github.blog/changelog/2020-12-08-dark-mode-public-beta/). Syntax colors and variables are inspired by Primer’s [github-syntax-light](https://github.com/primer/github-syntax-light) and [github-syntax-dark](https://github.com/primer/github-syntax-dark).

⚙️ By default, the Catalyst website color scheme follows the OS setting. To use a specific scheme (ignoring the OS setting), append either `?prefers-color-scheme=light` or `?prefers-color-scheme=dark` to any Catalyst URL. To resume following the OS setting, append `?prefers-color-scheme=`.

ℹ️ This PR also fixes a minor issue with note block sizing in https://github.com/github/catalyst/pull/91/commits/28662a92d1d780d0a30e61c93bd7b5feb4b29f2b, which can be observed in the second row of screenshots below.

### Screenshots

| Current Site | This PR: Light | This PR: Dark |
|:---:|:---:|:---:|
| current-site-home | this-pr-light-home | this-pr-dark-home |
| current-site-first-component | this-pr-light-first-component | this-pr-dark-first-component |
| current-site-targets | this-pr-light-targets | this-pr-dark-targets |

### CODE REVIEW

**Comment by koddsson** [comment]
<details>

<summary>I could not see the correct highlighting when I viewed the page.</summary>

image

</details>

<details>

<summary>Testing in Lighthouse it seems that we have a contrast regression compared to the light version.</summary>

image

</details>

**Review by keithamus — COMMENTED** [review]
This would be great! But yes let's test thoroughly and make sure we keep contrast ratios nice and usable :+1:

**Comment by smockle** [comment]
From @koddsson in https://github.com/github/catalyst/pull/91#issuecomment-740645939:
> Testing in Lighthouse it seems that we have a contrast regression compared to the light version.

From @keithamus in https://github.com/github/catalyst/pull/91#pullrequestreview-547452113:
> This would be great! But yes let's test thoroughly and make sure we keep contrast ratios nice and usable 👍

Completely agreed! I’d listed the item below under “TO DO” in the PR description—I’ll review all Lighthouse accessibility output, not just that related to contrast:

> **TO DO**
> 
> - Check the luminosity color contrast ratios (of e.g. body text and syntax-highlighted code on the new backgrounds) to ensure we meet or exceed [WCAG 2.2 Success Criterion 1.4.3 — Contrast (Minimum)](https://www.w3.org/TR/WCAG22/#contrast-minimum).

**Comment by smockle** [comment]
> I could not see the correct highlighting when I viewed the page.
> image

👍 Chrome (unlike Safari) didn’t vary `buttonText` when a dark color scheme is preferred (applied), so I replaced it with `var(--color-text-primary)` in https://github.com/github/catalyst/pull/91/commits/394b3f57bb7c47d2fc87067ccefa6563af58b79c

**Comment by koddsson** [comment]
image

Looks like it's rendering correctly for me now but Lighthouse is still complaining about sufficient contrast ratio. Does the CI check not check the site in dark mode?

**Comment by smockle** [comment]
> Does the CI check not check the site in dark mode?

It does not. This is discussed in https://github.com/GoogleChrome/lighthouse/issues/7751 (which is indirectly related).

Planned workaround:
1. Configure Lighthouse CI to visit http://127.0.0.1:4000?prefers-color-scheme=dark
2. Use JS to add a class or data attribute to `body` when this query param is provided (optionally storing the preference in localStorage)
3. Update `custom.css` to additionally set the current `@media (prefers-color-scheme: dark)` variables when `body[data-prefers-color-scheme=dark]`.

**Comment by smockle** [comment]
> > Does the CI check not check the site in dark mode?
> 
> It currently does not. This is discussed in [GoogleChrome/lighthouse#7751](https://github.com/GoogleChrome/lighthouse/issues/7751) (which is indirectly related).
> 
> Planned next steps:
> 
> 1. Configure Lighthouse CI to (additionally) visit http://127.0.0.1:4000?prefers-color-scheme=dark
> 2. Use JS to add a class or data attribute to `body` when this query param is provided (optionally storing the preference in localStorage)
> 3. Update `custom.css` to set color variables for both `@media (prefers-color-scheme: dark)` and `body[data-prefers-color-scheme=dark]`.

Update: This is done!

* https://github.com/github/catalyst/pull/91/commits/810a36beaccf03081728f86b6743569f3fca71a4 added support for `?prefers-color-scheme` query params
* https://github.com/github/catalyst/pull/91/commits/6f4cdaecf2ef6904d8a3e25863bcfc681945a891 configured Lighthouse CI to test both color schemes
* https://github.com/github/catalyst/pull/91/commits/19d3eacd9e2202b1a9b55726045c62f31e33f763 updated the syntax themes to achieve a 100 in Lighthouse CI’s Accessibility audit.

**Comment by smockle** [comment]
I’ve updated the description and screenshots in the PR description — @koddsson and @keithamus, this is ready for another review. 🎊

**Review by keithamus — APPROVED** [review]
This is some excellent work :+1:. Let's get this merged :smile:

**Pull request merged**
